spring.liveBeansView.mbeanDomain: default
spring:
  profiles.active: default
---
spring:
  profiles: default

spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://localhost:3306/userCrud
spring.datasource.username: root
spring.datasource.password: 
spring.datasource.platform: mysql
spring.datasource.initialize: false
spring.datasource.tomcat.max-wait: 20000
spring.datasource.tomcat.max-active: 50
spring.datasource.tomcat.max-idle: 20
spring.datasource.tomcat.min-idle: 15
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
spring.jpa.properties.hibernate.id.new_generator_mappings: false
spring.jpa.properties.hibernate.format_sql: true
logging.level.org.hibernate.SQL: ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE 
elasticsearch.url: http://localhost:9200/_bulk

---
spring:
   profiles: test

spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
spring.datasource.url: jdbc:h2:~/test;AUTO_SERVER=TRUE
spring.jpa.hibernate.ddl-auto: create
spring.jpa.show-sql: false 
spring.jpa.properties.hibernate.id.new_generator_mappings: false
spring.jpa.properties.hibernate.format_sql: true
elasticsearch.url: http://localhost:9200/_bulk

---
spring:
  profiles: container

spring.datasource.driver-class-name: com.mysql.jdbc.Driver
spring.datasource.url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
spring.datasource.username: ${DATABASE_USER}
spring.datasource.password: ${DATABASE_PASSWORD}
spring.datasource.platform: mysql
spring.datasource.initialize: true
spring.datasource.tomcat.max-wait: 20000
spring.datasource.tomcat.max-active: 50
spring.datasource.tomcat.max-idle: 20
spring.datasource.tomcat.min-idle: 15
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: create
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
spring.jpa.properties.hibernate.id.new_generator_mappings: false
spring.jpa.properties.hibernate.format_sql: true
logging.level.org.hibernate.SQL: ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
elasticsearch.url: ${ELASTIC_SEARCH_URL}
